package com.sylhetic.token;

public enum TokenType {
    NEWLINE, INDENT, DEDENT, EOF,

    IDENTIFIER, INT, FLOAT, STRING,

    DHORO, JUDI, ARJUDI, ANNAY, JOTOBIL, LAGIRWO, BHITORE,
    ATKIJAO, CHALAIYAJAAO, FUNCTION, RETURN,
    AND, OR, NOT, TRUE, FALSE, NONE,
    TYPE_INT, TYPE_FLOAT, TYPE_STRING, TYPE_BOOL,

    OUTPUT, INPUT, RANGE, MIN, MAX, ROUND,

    COLON, COMMA, LPAREN, RPAREN, ARROW,
    PLUS, MINUS, STAR, SLASH, PERCENT,
    ASSIGN, EQEQ, NEQ, GT, LT, GTE, LTE
}
